services:
  mysql:
    image: mysql:8.0
    container_name: meditracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meditracker
      MYSQL_USER: meditracker
      MYSQL_PASSWORD: meditracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
    ports:
      - "8080:8080"

  adminer:
    image: adminer:4
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"

volumes:
  mysql_data: