spring:
  datasource:
    url: jdbc:mysql://mysql:3306/meditracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: meditracker
    password: meditracker
  jpa:
    hibernate:
      ddl-auto: update   # set to 'none' if you import your own schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger