spring:
  datasource:
    url: jdbc:h2:file:./meditracker-db;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 0
    open-in-view: false
    show-sql: true
  transaction:
    default-timeout: 30
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    path: /swagger