spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meditracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: meditracker
    password: meditracker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080
